// Top-level build file where you can add configuration options common to all sub-projects/modules.buildscript {
//
buildscript {
    ext {
        agp_version = '8.5.2'
        agp_version1 = '8.7.0'
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies{
        ext.kotlin_version = '1.8.0'
        classpath "com.android.tools.build:gradle:$agp_version1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}